In [1]:
from game import select_move_easy, get_bin_board, popcount
import numpy as np

In [2]:
def log_to_list():
    with open("chess_log.txt", "r") as f:
        data = f.read()
    return eval(data)

In [3]:
log = log_to_list()
board = np.array(log[5])
print(board)

select_move_easy(board, 1, 7)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  1  1 -1  0]
 [ 0  0  0  0  1  0 -1  0]
 [ 0  0  0  0  0  0 -1  0]]
(7, 7) -3992
(5, 7) -176
(5, 3) -128
(4, 2) -128
(3, 5) -128
(3, 2) -128
(2, 4) -128


(5, 3)

In [4]:
from numpy import uint64 as u64
import numpy as np
mask_all = u64(0xffff_ffff_ffff_ffff)

mask_corner = u64(0x8100_0000_0000_0081)  # 角
mask_star = u64(0x4281_0000_0000_8142)  # 角旁边的两个位置
mask_inner = mask_all ^ (mask_corner | mask_star)  # 其他位置
hex(mask_inner)

'0x3c7effffffff7e3c'

In [5]:
board = np.full((8, 8), -1)
board[0, 0] = board[6, 0] = board[0, :] = 1
board[7, 0] = 0

board

array([[ 1,  1,  1,  1,  1,  1,  1,  1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [ 1, -1, -1, -1, -1, -1, -1, -1],
       [ 0, -1, -1, -1, -1, -1, -1, -1]])

In [6]:
select_move_easy(board, -1, max_depth=6)

(7, 0) -50331648


(7, 0)

In [7]:
board =np.array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, -1, 0, 0, 0, 0, 0, 0],
       [0, 1, -1, -1, -1, -1, 0, 0],
       [1, 1, 1, -1, -1, -1, 0, 0],
       [1, 1, -1, 1, -1, -1, 0, 0],
       [1, 1, 1, -1, 1, -1, 0, 0],
       [-1, -1, -1, -1, -1, -1, -1, 0],
       [0, -1, -1, 0, 0, -1, 1, 0]])

board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  1, -1, -1, -1, -1,  0,  0],
       [ 1,  1,  1, -1, -1, -1,  0,  0],
       [ 1,  1, -1,  1, -1, -1,  0,  0],
       [ 1,  1,  1, -1,  1, -1,  0,  0],
       [-1, -1, -1, -1, -1, -1, -1,  0],
       [ 0, -1, -1,  0,  0, -1,  1,  0]])

In [8]:
select_move_easy(board, 1, 6)

(7, 0) 4640
(7, 4) 4288
(7, 3) 4512
(5, 6) 4384
(4, 6) 4384
(3, 6) 4336
(2, 6) 4144
(1, 6) 4288
(1, 5) 4240
(1, 4) 4208
(1, 3) 4288
(1, 2) 4320
(0, 1) 4560


(7, 0)

In [9]:
(u64(1) - u64(0)) << u64(20)

1048576

In [10]:
board = np.array(
    [[0,  0,  0, 1,  -1,  -1,  -1,  0],
    [0,  0,  0,  0,  0,  1,  -1,  -1],
    [0,  0,  0,  0,  0,  1,  1,  1],
    [0,  0,  0,  0, 0,  0,  0,  -1],
    [0,  0,  0, 0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0]])

select_move_easy(board, 1, 6)

(0, 7) -13631488
(4, 7) -4128


(4, 7)

### 逐个删除

In [11]:
board =np.array([
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0, -1, -1,  0,  0],
    [ 1,  1, -1,  1, -1, -1,  0,  0],
    [ 1,  1,  1, -1,  1, -1,  0,  0],
    [-1, -1, -1, -1, -1, -1,  0,  0],
    [ 0, -1, -1,  0,  0, -1,  1,  0]])

b, w = get_bin_board(board)
print(popcount(b), popcount(w))

select_move_easy(board, 1, 6)

16 8
(7, 0) 7904
(7, 4) 3872
(7, 3) 3904
(5, 6) 4232
(4, 6) 4232
(3, 6) 3792
(3, 3) 3904
(3, 2) 3920
(2, 5) 3920
(2, 4) 4136


(7, 0)

In [12]:
board =np.array([
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0, -1, -1,  0,  0],
    [ 1,  1, -1,  1, -1, -1,  0,  0],
    [ 1,  1,  1, -1,  1, -1,  0,  0],
    [-1, -1, -1, -1, -1, -1,  0,  0],
    [ 0, -1, -1,  0,  0, -1,  1,  0]])

b, w = get_bin_board(board)
print(popcount(b), popcount(w))

select_move_easy(board, 1, 6)

16 8
(7, 0) 7904
(7, 4) 3872
(7, 3) 3904
(5, 6) 4232
(4, 6) 4232
(3, 6) 3792
(3, 3) 3904
(3, 2) 3920
(2, 5) 3920
(2, 4) 4136


(7, 0)