In [1]:
from game import select_move_easy
import numpy as np

In [2]:
def log_to_list():
    with open("chess_log.txt", "r") as f:
        data = f.read()
    return eval(data)

In [3]:
log = log_to_list()
board = np.array(log[5])
print(board)

select_move_easy(board, 1, 7)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  1  1 -1  0]
 [ 0  0  0  0  1  0 -1  0]
 [ 0  0  0  0  0  0 -1  0]]
(2, 4) -144
(3, 2) -48
(3, 5) -48
(4, 2) -48
(5, 3) -40
(5, 7) -48
(7, 7) -3792


(5, 3)

In [4]:
from numpy import uint64 as u64
import numpy as np
mask_all = u64(0xffff_ffff_ffff_ffff)

mask_corner = u64(0x8100_0000_0000_0081)  # 角
mask_star = u64(0x4281_0000_0000_8142)  # 角旁边的两个位置
mask_inner = mask_all ^ (mask_corner | mask_star)  # 其他位置
hex(mask_inner)

'0x3c7effffffff7e3c'

In [5]:
board = np.full((8, 8), -1)
board[0, 0] = board[6, 0] = board[0, :] = 1
board[7, 0] = 0

board

array([[ 1,  1,  1,  1,  1,  1,  1,  1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [ 1, -1, -1, -1, -1, -1, -1, -1],
       [ 0, -1, -1, -1, -1, -1, -1, -1]])

In [6]:
select_move_easy(board, -1, max_depth=6)

(7, 0)

In [7]:
board =np.array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, -1, 0, 0, 0, 0, 0, 0],
       [0, 1, -1, -1, -1, -1, 0, 0],
       [1, 1, 1, -1, -1, -1, 0, 0],
       [1, 1, -1, 1, -1, -1, 0, 0],
       [1, 1, 1, -1, 1, -1, 0, 0],
       [-1, -1, -1, -1, -1, -1, -1, 0],
       [0, -1, -1, 0, 0, -1, 1, 0]])

board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  1, -1, -1, -1, -1,  0,  0],
       [ 1,  1,  1, -1, -1, -1,  0,  0],
       [ 1,  1, -1,  1, -1, -1,  0,  0],
       [ 1,  1,  1, -1,  1, -1,  0,  0],
       [-1, -1, -1, -1, -1, -1, -1,  0],
       [ 0, -1, -1,  0,  0, -1,  1,  0]])

In [19]:
select_move_easy(board, 1, 6)

(0, 1) 424
(1, 2) 320
(1, 3) 304
(1, 4) 288
(1, 5) 288
(1, 6) 200
(2, 6) 224
(3, 6) 240
(4, 6) 304
(5, 6) 8
(7, 3) 544
(7, 4) 264
(7, 0) 4640


(7, 0)

In [9]:
(u64(1) - u64(0)) << u64(20)

1048576