In [1]:
from game import *
import numpy as np

In [2]:
def log_to_list():
    with open("chess_log.txt", "r") as f:
        data = f.read()
    return eval(data)

In [3]:
log = log_to_list()
board = np.array(log[5])
print(board)

select_move_easy(board, 1, 7)

FileNotFoundError: [Errno 2] No such file or directory: 'chess_log.txt'

In [ ]:
from numpy import uint64 as u64
import numpy as np
mask_all = u64(0xffff_ffff_ffff_ffff)

mask_corner = u64(0x8100_0000_0000_0081)  # 角
mask_star = u64(0x4281_0000_0000_8142)  # 角旁边的两个位置
mask_inner = mask_all ^ (mask_corner | mask_star)  # 其他位置
hex(mask_inner)

'0x3c7effffffff7e3c'

In [4]:
board = np.full((8, 8), -1)
board[0, 0] = board[6, 0] = board[0, :] = 1
board[7, 0] = 0

board

array([[ 1,  1,  1,  1,  1,  1,  1,  1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [ 1, -1, -1, -1, -1, -1, -1, -1],
       [ 0, -1, -1, -1, -1, -1, -1, -1]])

In [ ]:
select_move_easy(board, -1, max_depth=6)

(7, 0) -50331648


(7, 0)

In [ ]:
board =np.array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, -1, 0, 0, 0, 0, 0, 0],
       [0, 1, -1, -1, -1, -1, 0, 0],
       [1, 1, 1, -1, -1, -1, 0, 0],
       [1, 1, -1, 1, -1, -1, 0, 0],
       [1, 1, 1, -1, 1, -1, 0, 0],
       [-1, -1, -1, -1, -1, -1, -1, 0],
       [0, -1, -1, 0, 0, -1, 1, 0]])

board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  1, -1, -1, -1, -1,  0,  0],
       [ 1,  1,  1, -1, -1, -1,  0,  0],
       [ 1,  1, -1,  1, -1, -1,  0,  0],
       [ 1,  1,  1, -1,  1, -1,  0,  0],
       [-1, -1, -1, -1, -1, -1, -1,  0],
       [ 0, -1, -1,  0,  0, -1,  1,  0]])

In [ ]:
select_move_easy(board, 1, 6)

(0, 1) 120
(1, 2) -96
(1, 3) 72
(1, 4) 40
(1, 5) -32
(1, 6) 24
(2, 6) -120
(3, 6) 0
(4, 6) 16
(5, 6) -80
(7, 3) 120
(7, 4) 56
(7, 0) -7608


(0, 1)

In [ ]:
(u64(1) - u64(0)) << u64(20)

1048576

In [ ]:
board = np.array(
    [[0,  0,  0, 1,  -1,  -1,  -1,  0],
    [0,  0,  0,  0,  0,  1,  -1,  -1],
    [0,  0,  0,  0,  0,  1,  1,  1],
    [0,  0,  0,  0, 0,  0,  0,  -1],
    [0,  0,  0, 0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0]])

select_move_easy(board, 1, 6)

(4, 7) -7936
(0, 7) -13631488


(4, 7)

### 逐个删除

In [ ]:
board =np.array([
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0, -1, -1,  0,  0],
    [ 1,  1, -1,  1, -1, -1,  0,  0],
    [ 1,  1,  1, -1,  1, -1,  0,  0],
    [-1, -1, -1, -1, -1, -1,  0,  0],
    [ 0, -1, -1,  0,  0, -1,  1,  0]])

b, w = get_bin_board(board)
print(popcount(b), popcount(w))

select_move_easy(board, 1, 6)

16 8
(2, 4) -40
(2, 5) -40
(3, 2) -40
(3, 3) -8
(3, 6) -8
(4, 6) -8
(5, 6) -48
(7, 3) -8
(7, 4) -16
(7, 0) -3728


(3, 3)

In [ ]:
board =np.array([
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0, -1, -1,  0,  0],
    [ 1,  1, -1,  1, -1, -1,  0,  0],
    [ 1,  1,  1, -1,  1, -1,  0,  0],
    [-1, -1, -1, -1, -1, -1,  0,  0],
    [ 0, -1, -1,  0,  0, -1,  1,  0]])

# board[7, 6] 为 0 或 -1时，评分正常，为1时，评分不正常

b, w = get_bin_board(board)
print(popcount(b), popcount(w))

select_move_easy(board, 1, 6)

16 8
(2, 4) -40
(2, 5) -40
(3, 2) -40
(3, 3) -8
(3, 6) -8
(4, 6) -8
(5, 6) -48
(7, 3) -8
(7, 4) -16
(7, 0) -3728


(3, 3)

In [ ]:
board =np.array([
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0, -1, -1,  0,  0],
    [ 1,  1, -1,  1, -1, -1,  0,  0],
    [ 1,  1,  1, -1,  1, -1,  0,  0],
    [-1, -1, -1, -1, -1, -1,  0,  0],
    [ 0, -1, -1,  0,  0, -1,  1,  0]])


b, w = get_bin_board(board)
print(popcount(b), popcount(w))

select_move_easy(board, 1, 6)

16 8
(2, 4) -40
(2, 5) -40
(3, 2) -40
(3, 3) -8
(3, 6) -8
(4, 6) -8
(5, 6) -48
(7, 3) -8
(7, 4) -16
(7, 0) -3728


(3, 3)

In [ ]:
# 1 和 -1 都可以放右上角
board = np.array([
    [ 0,  1, -1,  0, -1, -1, -1,  0],
    [ 0,  0,  0,  0,  0, -1,  1, -1],
    [ 0,  0,  0,  0,  0, -1, -1, -1],
    [ 0,  0,  0,  0,  0,  0,  0, -1],
    [ 0,  0,  0,  0,  0,  0,  0, -1],
    [ 0,  0,  0,  0,  0,  0,  0, -1],
    [ 0,  0,  0,  0,  0,  0,  0,  1],
    [ 0,  0,  0,  0,  0,  0,  0,  0]
])

select_move_easy(board, 1, 2)

(0, 3) 3896
(1, 4) 72
(3, 4) 56
(3, 6) 88
(0, 7) -4048


(0, 3)

In [ ]:
mask_high_one = u64(0x8000_0000_0000_0000)
hex(mask_high_one >> u64(50))

'0x2000'

In [ ]:
-1 << 10

-1024

In [ ]:
b, w = frontier(*get_bin_board(INIT_BOARD))
print(INIT_BOARD)
print(get_2d_board(b))
print(get_2d_board(w))

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
from random import shuffle
a = [i for i in range(20)]
shuffle(a)
a

[17, 9, 5, 0, 10, 8, 19, 11, 18, 4, 12, 3, 13, 1, 7, 2, 6, 14, 16, 15]

In [10]:
-np.linalg.norm(np.array([0 ,0]) - np.array([8 / 2, 8 / 2]))

-5.656854249492381