In [2]:
import numpy as np

## Practice

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [14]:
#1
m = np.zeros((10, 10))
m[0, :] = m[:, 0] = m[m.shape[0] - 1, :] = m[:, m.shape[1] - 1] = 1
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [8]:
#2
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [16]:
#3
np.tile([[0, 1], [1, 0]], (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [26]:
#4
arr = np.arange(10)
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix 

In [71]:
#5
a = np.random.rand(5, 5)
nor = (a - np.mean(a)) / np.std(a)
a, nor

(array([[0.14282765, 0.10992318, 0.53240462, 0.88967572, 0.73738522],
        [0.74248004, 0.93218686, 0.17477833, 0.15542793, 0.36357179],
        [0.01533608, 0.69071505, 0.22093057, 0.57538365, 0.95459564],
        [0.29741751, 0.98279118, 0.76701543, 0.08494154, 0.64409124],
        [0.63505991, 0.99626661, 0.82055881, 0.90085168, 0.004709  ]]),
 array([[-1.16712837, -1.26509074, -0.00728929,  1.05636953,  0.60297398],
        [ 0.61814214,  1.18293268, -1.07200557, -1.12961511, -0.50993427],
        [-1.54669316,  0.46402867, -0.93460225,  0.12066683,  1.24964755],
        [-0.7068872 ,  1.33359061,  0.69118831, -1.33946547,  0.32522141],
        [ 0.29833354,  1.37370933,  0.85059636,  1.08964233, -1.57833184]]))

6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [77]:
#6
x = np.random.randn(10)
y = np.random.randn(10)

r = (x ** 2 + y ** 2) ** (0.5) 
p1 = np.arctan2(y, x)
p2 = np.arctan2(y, x) * 180 / np.pi

x, y, r, p1, p2

(array([ 1.32594791, -1.81488632, -0.42911223,  0.20423453,  0.25347684,
        -0.31562479, -0.31159246, -1.43152229, -1.60202537, -0.90809207]),
 array([-0.45601762,  0.27122364, -0.61604261, -0.60368979, -0.23215438,
        -1.04131417,  0.23352053,  0.59009222, -2.23685773, -1.03331298]),
 array([1.40217328, 1.83504077, 0.75076348, 0.63730142, 0.34372397,
        1.08809659, 0.38938631, 1.54837492, 2.75136653, 1.37563328]),
 array([-0.3312465 ,  2.99324664, -2.17921157, -1.24457312, -0.74151966,
        -1.86509689,  2.49844864,  2.75060229, -2.19230865, -2.29178357]),
 array([ -18.9790262 ,  171.50039941, -124.85962538,  -71.30878696,
         -42.48594714, -106.86218039,  143.15056263,  157.59790247,
        -125.61003288, -131.30952612]))

7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]

In [57]:
#7
a1 = np.arange(1, 6)
nz = 3
a2 = np.zeros(len(a1) + (len(a1) - 1) * (nz))
a2[::nz + 1] = a1
a2

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

hint
- nan means not a number 
- 0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2)
First guess a result, then print the result, and finally find why

In [58]:
#8
0 * np.nan

nan

In [61]:
np.nan == np.nan

False

In [62]:
np.inf > np.nan

False

In [63]:
np.nan - np.nan

nan

In [72]:
np.nan in set([np.nan])

True

In [73]:
0.3 == 3 * 0.1

False

9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [74]:
#9
np.array(0) / np.array(0)

C:\Users\itbil\AppData\Local\Temp\ipykernel_20264\3765654225.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [75]:
np.array(0) // np.array(0)

C:\Users\itbil\AppData\Local\Temp\ipykernel_20264\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [76]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\itbil\AppData\Local\Temp\ipykernel_20264\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])