In [1]:
import numpy as np
from numpy import uint64 as u64
from game import *

# board = np.array([[ 0,  0,  0,  0,  0,  0,  0,  0],
#                   [ 0,  0,  0,  0, -1,  0,  0,  0],
#                   [ 0,  0,  0, -1, -1,  0,  0,  0],
#                   [ 0,  0, -1, -1, -1, -1,  0,  0],
#                   [ 0,  0,  1,  1,  1,  1, -1,  0],
#                   [ 0,  0,  0,  0,  1, -1,  0, -1],
#                   [ 0,  0,  0,  0,  0,  0,  0,  0],
#                   [ 0,  0,  0,  0,  0,  0,  0,  0]])


# INIT_BOARD = np.array([[0,  0,  0,  0,  0,  0,  0,  0],
#                       [0,  0,  0,  0,  0,  0,  0,  0],
#                       [0,  0,  0,  0,  0,  0,  0,  0],
#                       [0,  0,  0,  -1, 1,  0,  0,  0],
#                       [0,  0,  0, 1,  -1,  0,  0,  0],
#                       [0,  0,  0,  0,  0,  0,  0,  0],
#                       [0,  0,  0,  0,  0,  0,  0,  0],
#                       [0,  0,  0,  0,  0,  0,  0,  0]])


In [2]:
dir = "../../chess-log/board_txt/"
def log_to_list():
    with open(dir + "奇怪占角.txt", "r") as f:
        data = f.read()
    return np.array(eval(data))

In [3]:
log = log_to_list()
board = log[40]

board

array([[ 0,  1,  1,  1,  1,  1,  1,  0],
       [-1, -1,  1, -1, -1, -1, -1, -1],
       [-1,  1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1, -1, -1, -1, -1, -1],
       [ 0,  1,  1,  1, -1, -1,  0, -1],
       [ 0,  0,  1,  1,  1, -1,  0, -1],
       [ 0,  0,  0,  1,  1,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  1,  0]])

In [4]:
select_move_easy(board, 1)

(5, 6) -1024
(4, 6) -712
(0, 0) -560
(0, 7) -534
max_depth: 5
Try time: 0.09190600000147242
search again

(5, 6) -1056
(4, 6) -752
(0, 0) -672
(0, 7) -634
----------- 7


(0, 7)

In [6]:
mask_corner_parts = (
    u64(0xf0f0_f0f0_0000_0000),  # 左上
    u64(0x0f0f_0f0f_0000_0000),  # 右上
    u64(0x0000_0000_f0f0_f0f0),  # 左下
    u64(0x0000_0000_0f0f_0f0f),  # 右下
)

mask_udlr_lines = (
    u64(0x7e00_0000_0000_0000), # up
    u64(0x0000_0000_0000_007e), # down
    u64(0x0080_8080_8080_8000), # left
    u64(0x0001_0101_0101_0100), # down
)

for mask in mask_udlr_lines:
    print(get_2d_board(mask))

[[0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0]]
[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]]
