In [1]:
import numpy as np
from numpy import uint64 as u

board = np.array([[ 0,  0,  0,  0,  0,  0,  0,  0],
                  [ 0,  0,  0,  0, -1,  0,  0,  0],
                  [ 0,  0,  0, -1, -1,  0,  0,  0],
                  [ 0,  0, -1, -1, -1, -1,  0,  0],
                  [ 0,  0,  1,  1,  1,  1, -1,  0],
                  [ 0,  0,  0,  0,  1, -1,  0, -1],
                  [ 0,  0,  0,  0,  0,  0,  0,  0],
                  [ 0,  0,  0,  0,  0,  0,  0,  0]])


INIT_BOARD = np.array([[0,  0,  0,  0,  0,  0,  0,  0],
                      [0,  0,  0,  0,  0,  0,  0,  0],
                      [0,  0,  0,  0,  0,  0,  0,  0],
                      [0,  0,  0,  -1, 1,  0,  0,  0],
                      [0,  0,  0, 1,  -1,  0,  0,  0],
                      [0,  0,  0,  0,  0,  0,  0,  0],
                      [0,  0,  0,  0,  0,  0,  0,  0],
                      [0,  0,  0,  0,  0,  0,  0,  0]])
board = INIT_BOARD
# board = np.array([
#     [0, 0, 0, 0],
#     [0, -1,1, 0],
#     [0, 1, -1, 0],
#     [0, 0, 0, 0]
# ])


In [2]:
# 将棋盘转换成二进制
s = list('0' * 64)
for p in np.argwhere(board == -1):
    s[p[0] * 8 + p[1]] = '1'
black_bin_board = np.uint64(int(''.join(s), 2))

s = list('0' * 64)
for p in np.argwhere(board == 1):
    s[p[0] * 8 + p[1]] = '1'
white_bin_board = np.uint64(int(''.join(s), 2))
bin_board = (black_bin_board, white_bin_board)
bin_board

(68853694464, 34628173824)

In [3]:
my_board, opposite_board = bin_board
tmp = (my_board << u(8)) & opposite_board
tmp = (tmp << u(8)) & opposite_board | tmp
tmp = (tmp << u(16)) & opposite_board | tmp
tmp = (tmp << u(16)) & opposite_board | tmp

point = tmp << u(8)
point = point & (my_board | opposite_board)
point

print(point)
'{:064b}'.format(point)

0


'0000000000000000000000000000000000000000000000000000000000000000'

In [4]:
def change(a):
    a = u(10)



b = u(20)
change(b)

b.dtype



dtype('uint64')

In [5]:
from game import Game
import numpy as np

INIT_BOARD = np.array([[0,  0,  0,  0,  0,  0,  0,  0],
                      [0,  0,  0,  0,  0,  0,  0,  0],
                      [0,  0,  0,  0,  0,  0,  0,  0],
                      [0,  0,  0,  -1, 1,  0,  0,  0],
                      [0,  0,  0, 1,  -1,  0,  0,  0],
                      [0,  0,  0,  0,  0,  0,  0,  0],
                      [0,  0,  0,  0,  0,  0,  0,  0],
                      [0,  0,  0,  0,  0,  0,  0,  0]])

game = Game(INIT_BOARD)

# moves = game.get_legal_moves(-1)
# print(bin(moves))

for i in range(100000):
    game.get_legal_moves(1)

ImportError: cannot import name 'Game' from 'game' (t:\CS311-AI\Proj-Reversed-Reversi\bot_v_bot\new_AlphaBeta\game.py)

In [ ]:
board = INIT_BOARD


for i in range(100000):
    s = list('0' * 64)
    for p in np.argwhere(board == -1):
        s[p[0] * 8 + p[1]] = '1'
    black_bin_board = np.uint64(int(''.join(s), 2))
    # board[board != 1] = 0
    # board = board.reshape((64, ))
    # int(''.join([str(s) for s in board.tolist()]), 2)

    # int(''.join(list(map(lambda s: str(s), board.tolist()))), 2)
# str(board)

In [ ]:



for t in range(100000):
    [i for i, j in enumerate("{:064b}".format(68853694464)) if j == '1']
    # print(a)

In [ ]:
import numpy as np
board = np.array([[ 0,  0,  0,  0,  0,  0,  0,  0],
                  [ 0,  0,  0,  0, -1,  0,  0,  0],
                  [ 0,  0,  0, -1, -1,  0,  0,  0],
                  [ 0,  0, -1, -1, -1, -1,  0,  0],
                  [ 0,  0,  1,  1,  1,  1, -1,  0],
                  [ 0,  0,  0,  0,  1, -1,  0, -1],
                  [ 0,  0,  0,  0,  0,  0,  0,  0],
                  [ 0,  0,  0,  0,  0,  0,  0,  0]])

from game import *
black_board, white_board = get_bin_board(board)
black_board, white_board

(2278445824671744, 1007157248)

In [ ]:
moves = legal_moves(black_board, white_board)
print_2d_board(moves)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 1 0]
 [0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
select_move(black_board, white_board)

12

In [ ]:
def loop():
    a = 0
    for i in range(100000000):
        a += 1
    print(a)

loop()



100000000


In [ ]:
a = 0
def loop2():
    global a
    for i in range(100000000):
        a += 1
    print(a)

loop2()

100000000


In [ ]:
def log_to_list():
    with open("chess_log.txt", "r") as f:
        data = f.read()
    return eval(data)

In [ ]:


log = log_to_list()
board = log[5]



[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, -1, 0, 0, 0],
 [0, 0, 0, -1, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 1, -1, 0],
 [0, 0, 0, 0, 1, 0, -1, 0],
 [0, 0, 0, 0, 0, 0, -1, 0]]

In [ ]:
STONE_TO_CHAR = {
    0: ' . ',
    -1: ' x ',
    1: ' o ',
}

def print_board_2(board):
    for row in range(8):
        print("%2s %s" % (row, ''.join([STONE_TO_CHAR[board[row, col]] for col in range(8)])))
    print("    " + "  ".join(str(e) for e in range(8)))


In [ ]:
import numpy as np
board = np.array([[ 0,  0,  0,  0,  0,  0,  0,  0],
                  [ 0,  0,  0,  0, -1,  0,  0,  0],
                  [ 0,  0,  0, -1, -1,  0,  0,  0],
                  [ 0,  0, -1, -1, -1, -1,  0,  0],
                  [ 0,  0,  1,  1,  1,  1, -1,  0],
                  [ 0,  0,  0,  0,  1, -1,  0, -1],
                  [ 0,  0,  0,  0,  0,  0,  0,  0],
                  [ 0,  0,  0,  0,  0,  0,  0,  0]])

print_board_2(board)

 0  .  .  .  .  .  .  .  . 
 1  .  .  .  .  x  .  .  . 
 2  .  .  .  x  x  .  .  . 
 3  .  .  x  x  x  x  .  . 
 4  .  .  o  o  o  o  x  . 
 5  .  .  .  .  o  x  .  x 
 6  .  .  .  .  .  .  .  . 
 7  .  .  .  .  .  .  .  . 
    0  1  2  3  4  5  6  7
