In [1]:
from game import select_move_easy
import numpy as np
from .

In [2]:
def log_to_list():
    with open("chess_log.txt", "r") as f:
        data = f.read()
    return eval(data)

In [16]:
log = log_to_list()
board = np.array(log[5])
print(board)

select_move_easy(board, 1, 8)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  1  1 -1  0]
 [ 0  0  0  0  1  0 -1  0]
 [ 0  0  0  0  0  0 -1  0]]


(3, 2)