In [1]:
from game import select_move_easy, get_bin_board, popcount
import numpy as np

In [2]:
def log_to_list():
    with open("chess_log.txt", "r") as f:
        data = f.read()
    return eval(data)

In [3]:
log = log_to_list()
board = np.array(log[5])
print(board)

select_move_easy(board, 1, 7)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  1  1 -1  0]
 [ 0  0  0  0  1  0 -1  0]
 [ 0  0  0  0  0  0 -1  0]]
(2, 4) -160
(3, 2) -128
(3, 5) -128
(4, 2) -128
(5, 3) -128
(5, 7) -144
(7, 7) -3840


(3, 2)

In [4]:
from numpy import uint64 as u64
import numpy as np
mask_all = u64(0xffff_ffff_ffff_ffff)

mask_corner = u64(0x8100_0000_0000_0081)  # 角
mask_star = u64(0x4281_0000_0000_8142)  # 角旁边的两个位置
mask_inner = mask_all ^ (mask_corner | mask_star)  # 其他位置
hex(mask_inner)

'0x3c7effffffff7e3c'

In [5]:
board = np.full((8, 8), -1)
board[0, 0] = board[6, 0] = board[0, :] = 1
board[7, 0] = 0

board

array([[ 1,  1,  1,  1,  1,  1,  1,  1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [ 1, -1, -1, -1, -1, -1, -1, -1],
       [ 0, -1, -1, -1, -1, -1, -1, -1]])

In [6]:
select_move_easy(board, -1, max_depth=6)

(7, 0) -50331648


(7, 0)

In [7]:
board =np.array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, -1, 0, 0, 0, 0, 0, 0],
       [0, 1, -1, -1, -1, -1, 0, 0],
       [1, 1, 1, -1, -1, -1, 0, 0],
       [1, 1, -1, 1, -1, -1, 0, 0],
       [1, 1, 1, -1, 1, -1, 0, 0],
       [-1, -1, -1, -1, -1, -1, -1, 0],
       [0, -1, -1, 0, 0, -1, 1, 0]])

board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  1, -1, -1, -1, -1,  0,  0],
       [ 1,  1,  1, -1, -1, -1,  0,  0],
       [ 1,  1, -1,  1, -1, -1,  0,  0],
       [ 1,  1,  1, -1,  1, -1,  0,  0],
       [-1, -1, -1, -1, -1, -1, -1,  0],
       [ 0, -1, -1,  0,  0, -1,  1,  0]])

In [8]:
select_move_easy(board, 1, 6)

(0, 1) 248
(1, 2) 56
(1, 3) 224
(1, 4) 208
(1, 5) 120
(1, 6) 176
(2, 6) 40
(3, 6) 192
(4, 6) 192
(5, 6) 72
(7, 3) 232
(7, 4) 208
(7, 0) -15672


(0, 1)

In [9]:
(u64(1) - u64(0)) << u64(20)

1048576

In [10]:
board = np.array(
    [[0,  0,  0, 1,  -1,  -1,  -1,  0],
    [0,  0,  0,  0,  0,  1,  -1,  -1],
    [0,  0,  0,  0,  0,  1,  1,  1],
    [0,  0,  0,  0, 0,  0,  0,  -1],
    [0,  0,  0, 0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0]])

select_move_easy(board, 1, 6)

(4, 7) -16160
(0, 7) -13631488


(4, 7)

### 逐个删除

In [11]:
board =np.array([
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0, -1, -1,  0,  0],
    [ 1,  1, -1,  1, -1, -1,  0,  0],
    [ 1,  1,  1, -1,  1, -1,  0,  0],
    [-1, -1, -1, -1, -1, -1,  0,  0],
    [ 0, -1, -1,  0,  0, -1,  1,  0]])

b, w = get_bin_board(board)
print(popcount(b), popcount(w))

select_move_easy(board, 1, 6)

16 8
(2, 4) 104
(2, 5) 104
(3, 2) 104
(3, 3) 120
(3, 6) 120
(4, 6) 120
(5, 6) 104
(7, 3) 120
(7, 4) 120
(7, 0) -11912


(3, 3)

In [12]:
board =np.array([
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0, -1, -1,  0,  0],
    [ 1,  1, -1,  1, -1, -1,  0,  0],
    [ 1,  1,  1, -1,  1, -1,  0,  0],
    [-1, -1, -1, -1, -1, -1,  0,  0],
    [ 0, -1, -1,  0,  0, -1,  1,  0]])

# board[7, 6] 为 0 或 -1时，评分正常，为1时，评分不正常

b, w = get_bin_board(board)
print(popcount(b), popcount(w))

select_move_easy(board, 1, 6)

16 8
(2, 4) 104
(2, 5) 104
(3, 2) 104
(3, 3) 120
(3, 6) 120
(4, 6) 120
(5, 6) 104
(7, 3) 120
(7, 4) 120
(7, 0) -11912


(3, 3)

In [13]:
board =np.array([
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  0, -1, -1,  0,  0],
    [ 1,  1, -1,  1, -1, -1,  0,  0],
    [ 1,  1,  1, -1,  1, -1,  0,  0],
    [-1, -1, -1, -1, -1, -1,  0,  0],
    [ 0, -1, -1,  0,  0, -1,  1,  0]])


b, w = get_bin_board(board)
print(popcount(b), popcount(w))

select_move_easy(board, 1, 6)

16 8
(2, 4) 104
(2, 5) 104
(3, 2) 104
(3, 3) 120
(3, 6) 120
(4, 6) 120
(5, 6) 104
(7, 3) 120
(7, 4) 120
(7, 0) -11912


(3, 3)

In [14]:
# 1 和 -1 都可以放右上角
board = np.array([
    [ 0,  1, -1,  0, -1, -1, -1,  0],
    [ 0,  0,  0,  0,  0, -1,  1, -1],
    [ 0,  0,  0,  0,  0, -1, -1, -1],
    [ 0,  0,  0,  0,  0,  0,  0, -1],
    [ 0,  0,  0,  0,  0,  0,  0, -1],
    [ 0,  0,  0,  0,  0,  0,  0, -1],
    [ 0,  0,  0,  0,  0,  0,  0,  1],
    [ 0,  0,  0,  0,  0,  0,  0,  0]
])

select_move_easy(board, 1, 2)

(0, 3) 3888
(1, 4) 72
(3, 4) 72
(3, 6) 88
(0, 7) -12280


(0, 3)

In [15]:
mask_high_one = u64(0x8000_0000_0000_0000)
hex(mask_high_one >> u64(50))

'0x2000'