In [1]:
from game import *
import numpy as np
def print_board(board):
    STONE_TO_CHAR = {
        0: ' . ',
        -1: ' x ',
        1: ' o ',
    }
    for row in range(8):
        print("%2s %s" % (row, ''.join(
            [STONE_TO_CHAR[board[row, col]] for col in range(8)])))
    print("    " + "  ".join(str(e) for e in range(8)))

In [2]:
def log_to_list():
    dir = "../../chess-log/board_txt/chess_log.txt"
    with open(dir, "r") as f:
        data = f.read()
    return np.array(eval(data))

board = log_to_list()[38]
print_board(board)




 0  .  .  .  x  x  o  o  . 
 1  .  .  .  x  x  o  o  x 
 2  .  .  .  x  x  o  x  x 
 3  .  .  x  x  x  o  x  x 
 4  .  .  x  x  o  o  x  x 
 5  .  x  x  o  o  x  x  x 
 6  .  x  x  x  x  x  .  o 
 7  .  o  o  x  x  .  .  . 
    0  1  2  3  4  5  6  7


In [3]:
select_move_easy(board, 1)

(6, 0) 736
(7, 6) 1200
(1, 2) 512
(3, 1) 848
(4, 1) 464
(2, 1) 544
(2, 2) 752
(5, 0) 480
(7, 5) 1024
(0, 2) 720
(6, 6) 1264
(0, 7) 1504
(7, 0) -352
max_depth: 5
Try time: 0.2165934000000007
search again

(6, 0) 768
(7, 6) 1168
(2, 2) 768
(7, 5) 1104
(6, 6) 1216
(2, 1) 560
(5, 0) 512
(3, 1) 752
(1, 2) 1136
(4, 1) 560
(0, 2) 1216
(0, 7) 1360
(7, 0) -336


(0, 7)

In [ ]:
board = np.array([
    [0, 0, 0, 0, 0,-1,-1,-1],
    [0, 0, 0, 0, 0, 0,-1,-1],
    [0, 0, 0, 0, 0, 0, 0,-1],
    [0, 0, 0, 0, 0, 0, 0,-1],
    [0, 0, 0, 0, 0, 0, 0,-1],
    [0, 0, 0, 0, 0, 0, 0,-1],
    [0, 0, 0, 0, 0, 0, 0,-1],
    [0, 0, 0, 0, 0, 0, 0,-1]
])

board

print(get_stable(get_2d_board((get_bin_board(board)[0]))))
print()
print_board(board)

[2, 8, 0]

 0  .  .  .  .  .  x  x  x 
 1  .  .  .  .  .  .  x  x 
 2  .  .  .  .  .  .  .  x 
 3  .  .  .  .  .  .  .  x 
 4  .  .  .  .  .  .  .  x 
 5  .  .  .  .  .  .  .  x 
 6  .  .  .  .  .  .  .  x 
 7  .  .  .  .  .  .  .  x 
    0  1  2  3  4  5  6  7


In [ ]:
diag2full = np.zeros((8, 8), dtype=int)
for i in range(15):
    diagsum = 0
    if i <= 7:
        sind1 = i
        sind2 = 7
        jrange = i + 1
    else:
        sind1 = 7
        sind2 = 14 - i
        jrange = 15 - i
    for j in range(jrange):
        diagsum += abs(board[sind1 - j][sind2 - j])
    if diagsum == jrange:
        for k in range(jrange):
            diag2full[sind1 - j][sind2 - j] = True

diag2full

array([[0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
colfull = np.zeros((8, 8), dtype=int)
colfull[:, np.sum(abs(board), axis=0) == 8] = True
colfull

array([[0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
np.zeros((8, 8), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
def get_stable(board):
    stable = [0, 0, 0]
    # 角, 边, 八个方向都无空格
    cind1 = [0, 0, 7, 7]
    cind2 = [0, 7, 7, 0]
    inc1 = [0, 1, 0, -1]
    inc2 = [1, 0, -1, 0]
    stop = [0, 0, 0, 0]

    for i in range(4):
        a = cind1[i], cind2[i]
        if board[cind1[i], cind2[i]] == 1:
            stop[i] = 1
            stable[0] += 1
            for j in range(1, 7):
                a = cind1[i] + inc1[i] * j, cind2[i] + inc2[i] * j
                if board[cind1[i] + inc1[i] * j][cind2[i] + inc2[i] * j] != 1:
                    break
                else:
                    stop[i] = j + 1
                    stable[1] += 1
    for i in range(4):
        a = cind1[i], cind2[i]
        if board[cind1[i]][cind2[i]] == 1:
            for j in range(1, 7 - stop[i - 1]):
                a = cind1[i] + inc1[i] * j, cind2[i] + inc2[i] * j
                if board[cind1[i] - inc1[i - 1] * j][cind2[i] - inc2[i - 1] * j] != 1:
                    break
                else:
                    stable[1] += 1
    
    return stable

In [ ]:
list(reversed([bin_to_coord(i) for i in sorted_move(legal_moves(*get_bin_board(board, 1)))]))

[(7, 0),
 (0, 0),
 (7, 2),
 (5, 5),
 (5, 6),
 (6, 2),
 (6, 3),
 (7, 4),
 (6, 5),
 (7, 1)]

In [ ]:
None is None

True