In [1]:
from utils import get_zobrist
get_zobrist()

from gotypes import Player, Point

__all__ = ["HASH_CODE", "INIT_BOARD"]

HASH_CODE = {
    (Point(row=0, col=0), Player.black): 2289980335500564411,
    (Point(row=0, col=0), Player.white): 5029705470751529549,
    (Point(row=0, col=1), Player.black): 6333084298055126073,
    (Point(row=0, col=1), Player.white): 7794633687160500598,
    (Point(row=0, col=2), Player.black): 3872473272532234811,
    (Point(row=0, col=2), Player.white): 9129676604319917602,
    (Point(row=0, col=3), Player.black): 5420976099491598583,
    (Point(row=0, col=3), Player.white): 4509674573516390443,
    (Point(row=0, col=4), Player.black): 5537988761805779473,
    (Point(row=0, col=4), Player.white): 7221740581435621035,
    (Point(row=0, col=5), Player.black): 4597774674252994820,
    (Point(row=0, col=5), Player.white): 7573158101894082723,
    (Point(row=0, col=6), Player.black): 3896167362486480916,
    (Point(row=0, col=6), Player.white): 8808200917131043459,
    (Point(row=0, col=7), Player.black): 557

In [2]:
s = set([(1, 2), (3, 4)])
s

{(1, 2), (3, 4)}

In [13]:
import numpy as np

a = np.zeros((8, 8))
b = np.zeros((8, 8))
b[1, 1] = b[2, 2] = b[3, 3] = 10
a != b
c = np.argwhere(a != b)
c[1]

array([2, 2], dtype=int64)

In [39]:
b[((1, 1), (2, 2))]

array([0., 0.])

In [23]:
a = np.array([1, 0, 1])
(a == 0).sum()

1

In [35]:
from gotypes import Point

p = Point(1, 2)




Point(row=1, col=2)

In [30]:
a = []
for i in range(5000_0000):
    a.append(i)



In [34]:
a = np.zeros((5000_0000, ))
for i in range(5000_0000):
    a[i] = i

In [2]:
from game import GameState, Board, Move
from gotypes import Point

board = Board()
game_state: GameState = GameState.new_game()
moves = game_state.legal_moves()
for m in moves:
    print(m)

game_state = game_state.apply_move(moves[0])
# game_state.board.grid
# game_state.board.grid[moves[0].point]
# game_state.board.place_stones(game_state.next_player, Point(2, 4), [Point(3, 3)])
# game_state.board.grid[tuple(([Point(4, 3), Point(4, 3), Point(5, 5)]))] = 10
game_state.board.grid

C3
D2
E5
F4


array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [3]:
COLS = 'ABCDEFGH'
print("    " + "  ".join(str(e) for e in range(len(COLS))))

    0  1  2  3  4  5  6  7


In [20]:
tuple(([Point(4, 3), Point(4, 3)]))

(Point(row=4, col=3), Point(row=4, col=3))

In [26]:
[Point(4, 3)] + [Point(4, 3)]

[Point(row=4, col=3), Point(row=4, col=3)]

In [3]:
tuple(([Point(4, 3), Point(4, 3), Point(5, 5)]))

(Point(row=4, col=3), Point(row=4, col=3), Point(row=5, col=5))

In [15]:
# game_state.board.grid[[(4, 3), (3, 4), (5, 5)]] = 1

game_state.board.grid[np.array([(4, 3), (3, 4), (5, 5)])] = 1
game_state.board.grid

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
a = np.array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])
a[(1, 2), (2, 3)] = 1

b = np.array([(1, 2), (6, 3)])
b[:, 0], b[:, 1]

(array([1, 6]), array([2, 3]))

In [33]:
np.array([Point(4, 3), Point(4, 3), Point(5, 5)])


array([[4, 3],
       [4, 3],
       [5, 5]])

In [4]:
import numpy as np
a = np.array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

from submit import AI
ai = AI(8, 1, 5)
ai.go(a)

TypeError: 'method' object is not iterable